-- Tabela CATEGORIA_USUARIO
CREATE TABLE CATEGORIA_USUARIO (
    ID_CATEGORIA_USUARIO BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_CATEGORIA_USUARIO VARCHAR(100) NOT NULL
);

-- Tabela EMPRESA
CREATE TABLE EMPRESA (
    ID_EMPRESA BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_EMPRESA VARCHAR(100) NOT NULL,
    CNPJ_EMPRESA VARCHAR(20),
    ENDERECO_EMPRESA VARCHAR(100),
    NUMERO_TELEFONE_EMPRESA VARCHAR(15)
);

-- Tabela NIVEL_ACESSO
CREATE TABLE NIVEL_ACESSO (
    ID_NIVEL_ACESSO BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_NIVEL_ACESSO VARCHAR(50)
);

-- Tabela LOCALIDADE
CREATE TABLE LOCALIDADE (
    ID_LOCALIDADE BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_LOCALIDADE VARCHAR(50) NOT NULL
);

-- Tabela JORNADA_TRABALHO
CREATE TABLE JORNADA_TRABALHO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_JORNADA VARCHAR(50) NOT NULL
);

-- Tabela USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME_USUARIO VARCHAR(50) NOT NULL,
    ID_EMPRESA BIGINT,
    ID_NIVEL_ACESSO BIGINT,
    ID_CATEGORIA_USUARIO BIGINT,
    ID_JORNADA_TRABALHO BIGINT,
    TOLERANCIA_AREA_RESTRITA VARCHAR(10),
    HORA_INICIO_JORNADA_TRABALHO DATE,
    HORA_SAIDA_JORNADA_TRABALHO DATE,
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA),
    FOREIGN KEY (ID_NIVEL_ACESSO) REFERENCES NIVEL_ACESSO(ID_NIVEL_ACESSO),
    FOREIGN KEY (ID_CATEGORIA_USUARIO) REFERENCES CATEGORIA_USUARIO(ID_CATEGORIA_USUARIO),
    FOREIGN KEY (ID_JORNADA_TRABALHO) REFERENCES JORNADA_TRABALHO(ID)
);

-- Tabela OCORRENCIA
CREATE TABLE OCORRENCIA (
    ID_OCORRENCIA BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME_OCORRENCIA VARCHAR(50) NOT NULL,
    DESCRICAO_FORMULA VARCHAR(100)
);

-- Tabela MOVIMENTACAO
CREATE TABLE MOVIMENTACAO (
    ID_MOVIMENTACAO BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO BIGINT,
    DATA_ENTRADA DATE,
    DATA_SAIDA DATE,
    PERIODO_PERMANENCIA INTEGER,
    ID_OCORRENCIA BIGINT,
    ID_DATA_ESPECIAL BIGINT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_OCORRENCIA) REFERENCES OCORRENCIA(ID_OCORRENCIA)
);

-- Tabela BANCO_HORAS
CREATE TABLE BANCO_HORAS (
    ID_BANCO_HORAS BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO BIGINT,
    DATA_TRABALHADA DATE,
    QUANTIDADE_HORAS_TRABALHADAS NUMERIC(10, 2),
    SALDO_HORAS_TRABALHADAS NUMERIC(10, 2),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

-- Tabela CALENDARIO
CREATE TABLE CALENDARIO (
    ID_DATA_ESPECIAL BIGINT PRIMARY KEY AUTO_INCREMENT,
    TIPO_DATA VARCHAR(20),
    DESCRICAO_TIPO_DATA VARCHAR(100),
    DATA_ESPECIAL DATE
);

-- Tabela TIPO_DATA
CREATE TABLE TIPO_DATA (
    ID_TIPO_DATA BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_TIPO_DATA VARCHAR(50)
);
